name: Create Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PROD
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: bahmutov/npm-install@v1
        env:
          NODE_ENV: production
      - run: yarn build
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: covid-vaccin-progress-tracker
          zip_file: dist/lambda.zip
#          memory_size: 128
#          timeout: 10
#          handler: foobar
#          role: arn:aws:iam::xxxxxxxxxxx:role/test1234
#          runtime: nodejs12.x
