name: Create Release
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
        env:
          NODE_ENV: production
      - run: yarn test
      - run: yarn build
      - name: deploy to aws
        if: github.ref == 'refs/heads/main'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: covid-vaccin-progress-tracker
          zip_file: dist/lambda.zip
